### ISSUE TITLE
zest.releaser install breaks site-packages under Python 2 in some circumstances

### ISSUE THREAD

**Issue by mitchellrj** [zestsoftware/zest.releaser#113]
Reproduced in virtualenvs on Ubuntu Trusty and on OSX. Python 2.7, zest.releaser 5.1 (tar.gz installed from PyPI using pip)

Example traceback:
```
$ bin/pip install zest.releaser
...
Successfully installed zest.releaser
Cleaning up...
$ bin/python
Traceback (most recent call last):
  File "/.../lib/python2.7/site.py", line 703, in <module>
    main()
  File "/.../lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/.../lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/.../lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/.../lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
TypeError: module.__init__() argument 1 must be string, not unicode
```

Removing the package from site-packages makes it work again:
```
rm lib/python2.7/site-packages/zest.releaser-5.1-py2.7-nspkg.pth
```

Alternatively, installing by downloading the package source tarball, extracting it and running ``setup.py install`` also works as it does not create the ``.pth`` file which is where the problem lies.

**Comment by mitchellrj** [comment]
This bug was introduced in 552df66.

**Comment by mauritsvanrees** [comment]
Actually, it looks even worse for me (5.1 that is, not your stuff).  Installing zest.releaser 5.0 is fine.  But in a fresh 2.7 virtualenv on my Mac I get this for 5.1:

```
(v27)mauritsvanrees@procyon:v27 $ pip install zest.releaser
Traceback (most recent call last):
  File "/Users/mauritsvanrees/tmp/v27/bin/pip", line 7, in <module>
    from pip import main
  File "/Users/mauritsvanrees/tmp/v27/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.commands import commands, get_summaries, get_similar_commands
  File "/Users/mauritsvanrees/tmp/v27/lib/python2.7/site-packages/pip/commands/__init__.py", line 6, in <module>
    from pip.commands.bundle import BundleCommand
  File "/Users/mauritsvanrees/tmp/v27/lib/python2.7/site-packages/pip/commands/bundle.py", line 6, in <module>
    from pip.commands.install import InstallCommand
  File "/Users/mauritsvanrees/tmp/v27/lib/python2.7/site-packages/pip/commands/install.py", line 5, in <module>
    from pip.req import InstallRequirement, RequirementSet, parse_requirements
  File "/Users/mauritsvanrees/tmp/v27/lib/python2.7/site-packages/pip/req/__init__.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "/Users/mauritsvanrees/tmp/v27/lib/python2.7/site-packages/pip/req/req_install.py", line 30, in <module>
    from pip.utils import (
  File "/Users/mauritsvanrees/tmp/v27/lib/python2.7/site-packages/pip/utils/__init__.py", line 87, in <module>
    def rmtree(dir, ignore_errors=False):
  File "/Users/mauritsvanrees/tmp/v27/lib/python2.7/site-packages/pip/_vendor/retrying.py", line 47, in wrap
    @six.wraps(f)
AttributeError: 'module' object has no attribute 'wraps'
```

If I first install 5.0, and then 5.1, it works fine.
Weird: I tried it again and now it worked with 5.1 immediately...
Let's keep this error for posterity at least. If someone knows what is/was going on here, that would be nice.

**Comment by mauritsvanrees** [comment]
I don't get your traceback locally by the way. But fix looks good. Merged.
